#This is a file to contain lengthy text for the UI

app_title_text<-"US Covid 19 Deaths Dashboard"

app_purpose_text<-"The purpose of this app is to allow users to explore the CDC dataset on Covid deaths, carryout some basic exploratory data analysis, generate supervised learning models including a linear regression model, a regression tree model and a random forest model, to make predictions about Covid 19 deaths, and to subset and download data from the dataset as desired."

about_data_text<-"https://data.cdc.gov/NCHS/Provisional-Death-Counts-for-Influenza-Pneumonia-a/ynw2-4viq 
Briefly discuss the data and its source - providing a link to more information about the data"

tab_purpose_text<-"Tell the user the purpose of each tab (page) of the app"

lm_info_text<-"Linear regression provides a relatively simple way to predict a quantitative response. In a simple linear regression we use a single predictor $X$ to predict a response $Y$. In a simple linear model we have two unknown constants, $Beta_0$ represents the intercept and $Beta_1$ represents the slope. $Beta_0$ is the expected value of $Y$ when $X=0$. $Beta_1$ is the average change in $Y$ that is associated with an increase of one-unit of $X$. In linear regression we use our training data to produce estimated values for $Beta_0$ and $Beta_1$ which can then be used to make predictions on our test data."

tree_info_text<-"Regression tree models have several benefits. First, trees are fairly simple to understand and they provide easy to interpret output. Predictors do not need to be scaled for regression trees, although they can be scaled if desired. Trees can be constructed without the need to include statistical assumptions. Tree models also offer built in variable selection, without the need for the user to input specific interaction terms as was necessary in building a linear model. Regression trees are able to account for interaction between variables by the nature of how the model is constructed. In building a regression tree each split is determined by minimizing the RSS. For each step of the way, the regression tree model identifies the optimal split for the data at that point. At each step an inequality for a single variable is considered where the split occurs. Later on in the branching another variable will be considered. So, if we were looking at the impact of college education and income on percent registered to vote in an area the best split for the first node of the tree may be college educated less than 30% vs greater than 30%. The next split may use income less than $50,000 vs greater than $50,000 and so on, each time seeking to minimize the RSS value. In this way the regression tree model is very flexible and able to handle interaction among predictor variables without having to explicitly tell it to do so. 

There are several drawbacks to regression tree models as well. As a whole, regression trees tend to have high variance, where small changes in data can vastly change the resulting tree. They can be more impacted by outliers and even small changes in the data, than linear methods. This can lead to lower predictive ability as compared to linear methods, particularly when dealing with data that fits a linear model well. Additionally, there is no optimal algorithm for building regression trees. Trees use a greedy algorithm for splitting, looking at the best split at each step, but not for the model as a whole. There is also usually a need to prune the tree back  to prevent overfitting and to lower variance in order to make better predictions before the final model is determined."

rf_info_text<-"A random forest model is an ensemble model used to improve upon the weaknesses of a single tree and bagged tree model. A single tree model can have a high variance and can change dramatically based on small changes in the data. Ensemble methods can help to deal with this issue by creating many single tress and creating an average prediction based on all of the predictions of the trees that were created. The goal of this is to reduce the variance of the model, thereby increasing our model's predictive ability.

Random forest models create multiple trees from bootstrap samples and average the results, which provides a reduction in variability of predictions when compared to a single tree model. Random forests use a random subset of the predictors for each bootstrap sample/tree fit. At each step along the way the random forest model is only using a random subset (*m*) of predictors to choose from when splitting the data, as opposed to the entire set of *p* predictors in the data set. One of the core strengths of the random forest model is its ability to decorrelate the trees that are produced, which helps to decrease the resulting variance in our final model.  

The random forest model helps to avoid a problem that can arise if there is a single very strong predictor that exists in the data set. If there is a single strong predictor in the data set, every bootstrap tree is likely to use that predictor for its first split, resulting in bagged tree predictions that are more correlated to one another, and thereby giving a smaller reduction in the variance from aggregation. The same issue arises when there are a large number of highly correlated predictors in the data set as well, and this problem can be addressed by creating a random forest model with a small *m* value. As the goal of ensemble methods is to reduce variance in order to increase prediction success, when there is one strong predictor, or several correlated predictors, such as what we see in this dataset, we will likely want to select a random forest model over a bagged tree model.  

The random forest model essentially decorrelates our single trees. In the random forest model at each split the model is only allowed to consider a random subset of our predictor variables to use for that split. By creating a random subset of variables for the model to choose from, we prevent all models from converging on a few very similar trees, particularly when you have one strong predictor in your dataset. We can then use the trees created to generate predictions based on the average response of all trees in our model, leading to decreased variance as compared to both a single tree and bagged tree fit. 

A big disadvantage  of random forest, is that these methods can be costly to build, train and implement and will likely be more difficult to interpret than a linear model. 

In training the random forest model we are using cross-validation.  We are also using values of `1:3` for `mtry` to find the optimal model. Lowest RMSE value was used to identify the optimal model. We will train a final model to obtain the test MSE based on the test set."

model_options_text<-"Select your desired options below. When you have selected the options that you want for your models click on the button that says RUN ALL MODELS"

data_split_text<-"What percent of the dataset do you want to use to create your training data set? Select a value between 1% and 99% to decide what portion of the data you would like to use to train your model. The remaining data in the original data set will be used for the test data set to see how well your model performs on predicting new data. NOTE: The data set from the CDC is fairly large, and as a result the deafault value for the data split is to send 15% of the observations to the training set. You are free to choose any value between 1 and 99 that you would like for your data split, but larger training sets will result in increased computational time in the model training stage."

lm_vars_text<-"Select all variables that you want to include in your MLR model. Note that we are building a MLR model with no interaction terms. If no variables are selected a MLR model will be built using all variables."

tree_vars_text<-"Select all variables that you want to include in your regression tree model. If no variables are selected a regression tree model will be built using all variables."

rf_vars_text<-"Select all variables that you want to include in your random forest model. If no variables are selected a random forest model will be built using all variables."
